// 1교시 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {inspect:['yard',3,9],shot:'02-zelkova'},
 {talk:'guard',shotBefore:'02b-yard-gate'},
 {bump:['hall','R']},
 {talk:'jung',wrong:true,shotBefore:'03-teachers-office',shotChoice:'03a-teacher-question',shotTap:'03b-tap-word'},
 {talk:'principal',shotBefore:'04-principal-office'},
 {talk:'daon',wrong:true,shotBefore:'05-classroom-daon'},
 {check:()=>state.f.paidFine,msg:'fine paid'},
 {bump:['hall','F']},
 {talk:'mate'},
 {talk:'mate2'},
 {talk:'eraser',shotBefore:'06-eraser'},
 {check:()=>state.items.includes('복숭아 쪽지'),msg:'note found in the eraser sleeve'},
 {talk:'daonSeat'},
 {check:()=>state.f.lunch,msg:'lunch bell'},
 {bump:['hall','Q']},
 // both tiles of the two-tile cafeteria door must open (the playthrough found only the left one did)
 {walkTo:['hall',17,8]},
 {check:()=>{dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));setTimeout(()=>dispatchEvent(new KeyboardEvent('keyup',{key:'ArrowDown',bubbles:true})),120);return true},msg:'press down on the right cafeteria door tile'},
 {shot:'06c-cafe-door-right'},
 {shot:'06d-cafeteria-from-right-door'},
 {check:()=>ZID==='cafe'&&player.x===11,msg:'the right cafeteria door tile opens too'},
 {talk:'chan',wrong:true,shotBefore:'07-cafeteria',shotBuild:'07b-sentence-build'},
 {check:()=>state.items.includes('바나나우유'),msg:'banana milk'},
 {talk:'imo',wrong:true,shotBefore:'08-school-store'},
 {walkTo:['hall',24,8],then:'08c-broadcast-door'},
 {talk:'gureum',shotBefore:'09-broadcast-corner'},
 {check:()=>state.items.includes('폐부 안내문')&&!state.items.includes('바나나우유'),msg:'milk given, notice received'},
 {talk:'gureum'},
 {talk:'principal'},
 {check:()=>state.f.deal&&!state.items.includes('폐부 안내문'),msg:'the deal'},
 {talk:'chanC'},
 {talk:'jongnye',shotBefore:'10-jongnye'},
 {check:()=>state.f.crew3,msg:'crew of three'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'gureumH',shotSay:{text:'지지직',name:'11-speaker-crackles'}},
 {check:()=>state.f.done,msg:'chapter done'},
 {inspect:['hall',2,9],shot:'12-shoe-locker-note'},
 {talk:'guard'},
 {clock:26*3600e3},
 {inspect:['class',9,2],shot:'13-class-log-review'},
 {talk:'chanC'},
 {walkTo:['bcast',10,4],then:'14-broadcast-room'},
 {look:true,shot:'15-look'},
 {talklog:1,shot:'16a-talk-log'},
 {start:1,shot:'16b-start'},
 {taps:1,shot:'16c-taps'},
 {panel:1,shot:'16-log'},
 {chapters:1,shot:'17-chapters'},
 {walkTo:['cafe',3,3],then:'18-serving-line'},
 {walkTo:['class',1,11],then:'19-class-back'},
 {walkTo:['yard',11,5],then:'20-school-front'},
]
