// 1교시 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {check:()=>ZID==='yard'&&player.x<=8,msg:'the first view starts by the 느티나무'},
 {inspect:['yard',3,9],shot:'02-zelkova'},
 {talk:'guard',shotBefore:'02b-yard-gate'},
 {bump:['hall','R']},
 {talk:'jung',wrong:true,shotBefore:'03-teachers-office',shotChoice:'03a-teacher-question',shotTap:'03b-tap-word'},
 {talk:'principal',shotBefore:'04-principal-office'},
 {talk:'daon',wrong:true,shotBefore:'05-classroom-daon',shotSay:{text:'넷째 줄',name:'05-daon-last-line'}},
 {check:()=>state.f.paidFine,msg:'fine paid'},
 {check:()=>!!C.NPC.daonSeat.walk,msg:'다온 is walking back to her desk'},
 {pause:0,shot:'05a-daon-walks'},
 {pause:2600},
 {check:()=>!C.NPC.daonSeat.walk,msg:'…and arrives at her desk'},
 {inspect:['class',17,10],shot:'05b-piggy-bank'},
 {check:()=>C.questText().includes('내 자리'),msg:'objective: find my seat'},
 {talk:'seat',shotBefore:'05c-my-seat',shotSay:{text:'국어 시간',name:'05d-class-time'}},
 {check:()=>Object.values(state.lv).filter(L=>L.b>=1).length===2,msg:'class time (국어, 영어) practised two of my words before the bell'},
 {check:()=>state.f.seated&&C.questText().includes('떨어졌'),msg:'sat down; class started; eraser fell'},
 {check:()=>player.sit&&player.sit.npc===C.NPC.seat&&player.dir==='up',msg:'sitting on my chair, facing the board'},
 {talk:'eraser',shotBefore:'06-eraser'},
 {bump:['hall','F']},
 {talk:'mate',shotSay:{text:'오백 원 없어',name:'06b-sleeper-talks'}},  // asleep: z's over him, eyes shut in the portrait
 {talk:'mate2'},
 {check:()=>state.items.includes('복숭아 쪽지'),msg:'note found in the eraser sleeve'},
 {talk:'daonSeat'},
 {check:()=>state.f.lunch,msg:'lunch bell'},
 {bump:['hall','Q']},
 // both tiles of the two-tile cafeteria door must open (the playthrough found only the left one did)
 {walkTo:['hall',17,8]},
 {check:()=>{dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));setTimeout(()=>dispatchEvent(new KeyboardEvent('keyup',{key:'ArrowDown',bubbles:true})),120);return true},msg:'press down on the right cafeteria door tile'},
 {shot:'06c-cafe-door-right'},
 {shot:'06d-cafeteria-from-right-door'},
 {check:()=>ZID==='cafe'&&player.x===11&&player.y===1&&player.dir==='down',msg:'the right cafeteria door tile opens too; you arrive at the top, facing down'},
 {talk:'chan',wrong:true,shotBefore:'07-cafeteria',shotBuild:'07b-sentence-build'},
 {check:()=>cultureSeen.includes('teok'),msg:'찬\'s 생일턱 line adds the 생일 턱 문화 노트'},
 // the new note waits as a tappable chip until it's read; tapping it opens the 일지 on that note
 {pause:500},
 {check:()=>!$('noteChip').hidden&&$('noteChip').textContent.includes('턱'),msg:'a new 문화 노트 waits on the screen as a chip'},
 {pause:0,shot:'08a-note-chip'},
 {check:()=>{$('noteChip').click();return !$('panel').hidden&&!$('noteCard').hidden&&$('noteCard').textContent.includes('턱')&&$('noteChip').hidden},msg:'tapping the chip opens the 일지 on that note, and the chip goes away'},
 {pause:300,shot:'08b-note-open'},
 {check:()=>{cancel();return $('panel').hidden},msg:'B closes the 일지'},
 {check:()=>state.items.includes('바나나우유'),msg:'banana milk'},
 {check:()=>player.sit&&player.x===10&&player.y===6,msg:'sitting across the table from 찬'},
 {talk:'imo',wrong:true,shotBefore:'08-school-store'},
 {walkTo:['hall',24,8],then:'08c-broadcast-door'},
 {walkTo:['bcast',7,2]},
 {check:()=>ZID==='bcast',msg:'broadcast room entered through its top-wall door'},
 {talk:'gureum',shotBefore:'09-broadcast-corner'},
 {check:()=>state.items.includes('폐부 안내문')&&!state.items.includes('바나나우유'),msg:'milk given, notice received'},
 {talk:'gureum'},
 {talk:'principal'},
 {check:()=>state.f.deal&&!state.items.includes('폐부 안내문'),msg:'the deal'},
 {walkTo:['class',18,11]},
 {check:()=>ZID==='class'&&player.y===11,msg:'classroom entered at its back door'},
 {talk:'chanC'},
 {talk:'jongnye'},
 {check:()=>!state.f.crew3,msg:'the teacher only sends you to your seat'},
 {talk:'seat',shotBefore:'10-jongnye',shotSay:{text:'축제',name:'10b-jongnye-camera'}},
 {check:()=>!camT,msg:'camera back on the player after 종례'},
 {check:()=>state.f.crew3,msg:'crew of three'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'gureumH',shotSay:{text:'지지직',name:'11-speaker-crackles'}},
 {check:()=>state.f.done,msg:'chapter done'},
 {inspect:['hall',2,9],shot:'12-shoe-locker-note'},
 {talk:'guard'},
 {clock:26*3600e3},
 {inspect:['class',9,2],shot:'13-class-log-review'},
 {talk:'chanC'},
 {walkTo:['bcast',10,4],then:'14-broadcast-room'},
 {look:true,shot:'15-look'},
 {talklog:1,shot:'16a-talk-log'},
 {start:1,shot:'16b-start'},
 {taps:1,shot:'16c-taps'},
 {panel:1,shot:'16-log'},
 {chapters:1,shot:'17-chapters'},
 {walkTo:['cafe',3,3],then:'18-serving-line'},
 {walkTo:['class',1,11],then:'19-class-back'},
 {walkTo:['yard',11,5],then:'20-school-front'},
 {walkTo:['yard',27,7],then:'21-gym-outside'},
 // in-character review: with every word due, everyone who has a line asks it in their own voice, and it grades
 {reviewTour:Object.keys(C.ZONES),shotChoice:'99-review-in-voice'},
]
