// 2교시 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {look:true},
 {talk:'gureum',wrong:true,shotBefore:'02-broadcast-room',shotBuild:'02b-sentence-build'},
 {check:()=>state.f.poster&&state.items.includes('모집 포스터'),msg:'recruiting poster'},
 {bump:['yard','J']},
 {bump:['yard','G']},
 {inspect:['hall2',4,0],shot:'03a-music-window'},
 {talk:'student'},
 {talk:'hariM',wrong:true,shotBefore:'03-music-room',shotSay:{text:'얼었어요',name:'03b-hari-freezes'}},
 {check:()=>ghosts.length===1,msg:'하리 runs out of the music room'},
 {check:()=>state.f.metHari&&state.items.includes('명찰'),msg:'name tag dropped'},
 {talk:'jung',wrong:true,shotBefore:'04-teachers-office',shotTap:'04b-tap-word'},
 {check:()=>state.f.knowHari,msg:'teacher names her'},
 {greet:'chanG',wrong:true,shotBefore:'05-gym'},  // walking into the gym, 찬 talks first
 {talk:'teaser2'},
 {talk:'teaser',wrong:true,shotChoice:'06-stand-up',shotSay:{text:'공을 들고 나갔어요',name:'06b-seniors-last-line'}},
 {check:()=>ghosts.length===2,msg:'both 선배 walk out of the gym'},
 {pause:0,shot:'06c-seniors-leave'},
 {check:()=>state.f.stoodUp,msg:'stood up for her'},
 {talk:'hariG',shotSay:{text:'긴장해서',name:'07-hari-gym'}},
 {check:()=>state.f.afterSchool&&!state.items.includes('명찰'),msg:'tag returned, after school'},
 {walkTo:['street',12,3],then:'08-street'},
 {inspect:['street',10,2]},
 {talk:'chanB'},
 {talk:'owner',wrong:true,shotBefore:'09-bunsik'},
 {talk:'hariB',wrong:true,shotSay:{text:'포기할까요',name:'10-hari-give-up'}},
 {talk:'chanB',shotSay:{text:'부끄러워서',name:'11-joke'}},
 {talk:'daonB',wrong:true,shotSay:{text:'재촉하지 마',name:'12-daon-hurry'}},
 {check:()=>state.f.hariMaybe&&state.items.includes('하리 연락처')&&state.items.includes('생수'),msg:'contact + water'},
 {check:()=>!state.f.nextDay&&C.NPC.hariMic.hide()&&C.NPC.daonL.hide(),msg:'same evening: the crew is not in the 방송실 yet'},
 {walkTo:['hall',18,7],then:'12b-hall-doors'},
 {talk:'gureumL',wrong:true,shotBefore:'13-broadcast-evening'},
 {check:()=>state.f.nextDay&&state.f.ready&&!state.items.includes('생수')&&!state.items.includes('하리 연락처'),msg:'next day, ready to broadcast'},
 {bump:['yard','G']},
 {talk:'daonL',shotBefore:'13b-broadcast-crew'},
 {talk:'chanL'},
 {talk:'hariMic',wrong:true,shotSay:{text:'복도가 조용해졌어요',name:'14-on-air'},shotBuild:'14b-build'},
 {check:()=>state.f.crew4&&state.f.done&&!state.items.includes('모집 포스터'),msg:'crew of four, chapter done'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {inspect:['bcast',13,0],shot:'15-sayeon-cassette'},
 {talk:'chanL'},
 {talk:'student'},
 {clock:26*3600e3},
 {inspect:['bcast',7,2],shot:'16-laptop-review'},
 {talk:'gureumL'},
 {look:true,shot:'17-look'},
 {talklog:1,shot:'18a-talk-log'},
 {start:1,shot:'18b-start'},
 {taps:1,shot:'18c-taps'},
 {panel:1,shot:'18-log'},
 {chapters:1,shot:'19-chapters'},
 {walkTo:['music',10,5],then:'20-music-empty'},
 {walkTo:['gym',6,8],then:'21-gym-empty'},
 {walkTo:['hall',4,2],then:'22-teachers-office'},
 {walkTo:['bunsik',10,8],then:'23-bunsik-empty'},
 {walkTo:['street',20,8],then:'24-bus-stop'},
 {walkTo:['yard',27,7],then:'25-gym-outside'},
 {walkTo:['hall2',10,4],then:'26-second-floor'},
 // in-character review: with every word due, everyone who has a line asks it in their own voice, and it grades
 {reviewTour:Object.keys(C.ZONES),shotChoice:'99-review-in-voice'},
]
