// 3교시 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {talk:'gureum',wrong:true,shotBefore:'02-bcast-morning',shotTap:'02b-tap-word'},
 {check:()=>state.f.plan,msg:'plan: register the club'},
 {bump:['yard','G']},
 {talk:'daonBoard',shotBefore:'03-board-rule'},
 {talk:'imo'},
 {talk:'jung',wrong:true,shotBefore:'04-teachers-office',shotChoice:'04a-teacher-question'},
 {check:()=>state.f.formGot&&state.items.includes('동아리 등록 신청서'),msg:'form with four names'},
 {talk:'lib'},
 {talk:'reader'},
 {talk:'chanLib',wrong:true,shotBefore:'05-library-chan'},
 {check:()=>state.f.signed5,msg:'찬 signed'},
 {talk:'jung'},
 {check:()=>state.f.submitted&&!state.items.includes('동아리 등록 신청서'),msg:'form submitted'},
 {talk:'daonBoard',shotBefore:'06-notice-board'},
 {check:()=>state.f.posted,msg:'poster posted'},
 {talk:'box'},
 {talk:'chanRumor',wrong:true,shotBefore:'07-rumor'},
 {check:()=>state.f.rumor,msg:'the rumor'},
 {talk:'kid'},
 {talk:'gureum'},
 {talk:'lib',shotSay:{text:'서른 개',name:'08-comments'}},
 {check:()=>state.f.sawComments,msg:'saw the comments'},
 {talk:'daonB',wrong:true,shotBefore:'09-bcast-hurt'},
 {check:()=>state.f.toNR,msg:'practice is on'},
 {talk:'guard',wrong:true,shotBefore:'10-street'},
 {talk:'hariNR',shotBefore:'11-noraebang'},
 {talk:'chanNR',wrong:true},
 {check:()=>state.f.interrupt,msg:'찬 butts in'},
 {walkTo:['nr',14,5],then:'11b-nr-lobby'},
 {talk:'daonNR',shotBuild:'12-build'},
 {check:()=>state.f.apology,msg:'찬 apologised'},
 {talk:'gureumNR',wrong:true},
 {check:()=>state.f.secret,msg:'구름 shared his secret'},
 {talk:'chanBox'},
 {talk:'hariBox',shotSay:{text:'달콤한 냄새',name:'13-peach-letter'}},
 {check:()=>state.f.letter&&state.items.includes('복숭아 편지'),msg:'the peach letter'},
 {walkTo:['hall',4,7],then:'13b-follower'},
 {talk:'jung',shotSay:{text:'매점 이모다',name:'14-old-spelling'}},
 {check:()=>state.f.oldSpelling,msg:'old spelling'},
 {talk:'imo',wrong:true,shotBefore:'15-store'},
 {check:()=>state.f.juice&&state.items.includes('복숭아 주스'),msg:'peach juice'},
 {talk:'daonEnd'},
 {talk:'chanEnd'},
 {talk:'hariFin',wrong:true,shotSay:{text:'오늘의 사연',name:'16-on-air'}},
 {check:()=>state.f.aired&&!state.items.includes('복숭아 주스'),msg:'first 사연 aired'},
 {check:()=>state.badges.length===C.WORDS.length-1,msg:'all but the last word'},
 {talk:'gureumFin',shotSay:{text:'누구세요',name:'17-finale'}},
 {check:()=>state.f.done,msg:'chapter done'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'daonEnd'},
 {clock:26*3600e3},
 {inspect:['bcast',7,2],shot:'18-laptop-review'},
 {talk:'jung'},
 {look:true,shot:'19-look'},
 {talklog:1,shot:'20-talk-log'},
 {start:1,shot:'20b-start'},
 {taps:1,shot:'20c-taps'},
 {panel:1,shot:'21-log'},
 {chapters:1,shot:'22-chapters'},
 {walkTo:['hall',20,3],then:'23-board-poster'},
 {walkTo:['library',12,4],then:'24-library'},
 {walkTo:['cafe',19,4],then:'24b-shop-corner'},
 {walkTo:['street',5,6],then:'25-street-shops'},
 {bump:['street','O']},
 {walkTo:['bcast',10,4],then:'27-bcast-end'},
]
