// 4교시 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {inspect:['bcast',4,2],shot:'02-burnt-desk'},
 {talk:'daonA'},
 {talk:'gureumA',wrong:true,shotBefore:'03-bcast-morning',shotTap:'03b-tap-word'},
 {talk:'daonA',wrong:true,shotBuild:'04-build'},
 {check:()=>state.f.needFix,msg:'plan: ask 태식'},
 {bump:['yard','G']},
 {talk:'principal'},
 {talk:'kid'},
 {talk:'taesikO',shotBefore:'05-teachers-office'},
 {talk:'jung',wrong:true,shotChoice:'05a-counsel-question',shotSay:{text:'빡빡해요',name:'05b-counsel'}},
 {check:()=>state.f.counsel&&state.badges.includes('빡빡하다'),msg:'counsel done, after school'},
 {check:()=>cultureSeen.includes('go3'),msg:'태식\'s 상담 adds the 고3 문화 노트'},
 {talk:'guard',wrong:true},
 {talk:'hariT'},
 {talk:'chanT',shotBefore:'06-town'},
 {check:()=>state.f.gotPosters&&state.items.includes('광고 포스터'),msg:'posters in hand'},
 {talk:'silJang',shotBefore:'07-hagwon'},
 {talk:'mun',wrong:true,shotBefore:'08-stationery'},
 {talk:'bun',wrong:true},
 {talk:'pyeon',wrong:true,shotSay:{text:'전파상',name:'09-fuse'}},
 {check:()=>state.f.shopM&&state.f.shopB&&state.f.shopP&&state.items.includes('부품')&&!state.items.includes('광고 포스터'),msg:'three shops, fuse, posters used up'},
 {talk:'chanT'},
 {talk:'hgStudent'},
 {talk:'silJang'},
 {talk:'taesikH',wrong:true,shotSay:{text:'생초보 아니야',name:'10-taesik'}},
 {check:()=>state.f.taesikCome,msg:'태식 follows'},
 {walkTo:['yard',12,8],then:'11-follower'},
 {talk:'gureumF',wrong:true,shotBuild:'12-fix-build',shotSay:{text:'켜, 켜졌어요',name:'12b-fixed'}},
 {check:()=>state.f.fixed&&!state.items.includes('부품'),msg:'circuit fixed, fuse used'},
 {talk:'daonA'},
 {talk:'gureumF',wrong:true,shotSay:{text:'엄마',name:'13-phone'}},
 {check:()=>state.f.promise,msg:'promise to his parents, festival morning'},
 {talk:'chanP'},
 {talk:'principal',wrong:true,shotBefore:'14-principal-office'},
 {check:()=>state.f.warned,msg:'the 교장 warns them'},
 {talk:'chanP',shotSay:{text:'여학생이 마이크를',name:'15-yearbook-photo'}},
 {check:()=>state.f.clue&&state.items.includes('앨범 사진'),msg:'yearbook photo'},
 {talk:'gureumS',shotBefore:'16-festival-stage'},
 {talk:'daonS',wrong:true},
 {talk:'taesikS'},
 {talk:'hariS'},
 {talk:'chanS'},
 {talk:'crowd1'},
 {talk:'crowd2'},
 {talk:'jungY'},
 {talk:'guard'},
 {talk:'gureumS',wrong:true,shotSay:{text:'방송부예요',name:'17-live'}},
 {check:()=>state.f.live,msg:'on air'},
 {check:()=>state.badges.length===C.WORDS.length-3,msg:'all but the finale words'},
 {talk:'principalS',wrong:true,shotSay:{text:'제가 복숭아',name:'18-reveal'}},
 {check:()=>state.f.done&&!state.items.includes('앨범 사진'),msg:'chapter done'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'chanS'},
 {talk:'hariS'},
 {talk:'kid'},
 {clock:26*3600e3},
 {inspect:['bcast',7,2],shot:'19-laptop-review'},
 {inspect:['bcast',13,0],shot:'20-sayeon-note'},
 {talk:'jungY'},
 {check:()=>state.f.jungBye,msg:'정 선생님 after the show'},
 {talk:'jungY'},
 {inspect:['hall',25,9],shot:'20b-bcast-door-sign'},
 {walkTo:['hall',22,6],then:'20c-bcast-door'},
 {look:true,shot:'21-look'},
 {talklog:1,shot:'22-talk-log'},
 {start:1,shot:'22b-start'},
 {taps:1,shot:'22c-taps'},
 {panel:1,shot:'23-log'},
 {chapters:1,shot:'24-chapters'},
 {walkTo:['town',5,3],then:'25-town-shops'},
 {walkTo:['town',24,3],then:'26-academy'},
 {walkTo:['hagwon',8,4],then:'27-hagwon'},
 {walkTo:['yard',19,6],then:'28-stage'},
 {walkTo:['yard',4,10],then:'29-zelkova-lights'},
 {walkTo:['hall',13,3],then:'30-principal-office'},
 {walkTo:['hall2',16,3],then:'31-second-floor'},
]
